[build]
buildCommand = "npm install"
startCommand = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production" 